### PR TITLE
SDK review

### PR DESCRIPTION
**Pull request by ndrean**
This is the SDK version. Please review. Obg

### CODE REVIEW

**Review by nelsonic — COMMENTED** [review]
@ndrean where's the **`Elixir`** code? 🔍

**Comment by ndrean** [comment]
This is not the SSR. This is when using th SDK. There is almost no Elixir code when using it, just the JS I wrote.
Just a route and the corresponding controller. Isn't the readme clear?

**Review by nelsonic — APPROVED** [review]
Thanks for these updates. 👌

**Comment by ndrean** [comment]
Well, the JS code is good in the sens that the dialog works and it sends the users' paylaod to the server. I just came back to this Facebook login this evening and there is a problem with the SDK: a redirection problem. Both a POST with payload or GET with query string work but I can't redirect to a new page. Strange.
Meanwhile, I tested again the Google One Tap and this works perfectly. But... I used a shortcut with the JOSE library to decrypt the received token to get the users credentials. I works but I don't use Googles' PEM to verifythis token and I believe I should for good sake.
Finally, for the SSR version of the Facebook connect, the one with real Elixir code, this works perfectly apart the error handling. I will try to go closer to your code.

**Pull request merged**
